### ISSUE TITLE
Compiled test.cpp error

### ISSUE THREAD

**Issue by leemengxing** [SyGoing/LFFD-MNN#3]
Hello, I probably don't know much about c++. When I compiled test.cpp incorrectly, my command was g++ test.cpp-std=c++ 11 `pkg-config -- LIBS -- cflags opencv4`-I. /src. I link MNN libraries and header files at first level

**Comment by leemengxing** [comment]
![{3065DA4E-9208-459D-9E7B-53F9651385A5}_20191008111804](https://user-images.githubusercontent.com/24696984/66364892-bec23480-e9bd-11e9-8099-37a4cdd666cb.jpg)

**Comment by SyGoing** [comment]
I suggest you write the CMakeLists.txt to compile it , And please compile test.cpp and MNN_LFFD.cpp togethor

**Comment by leemengxing** [comment]
Thank you for your quick response. I'm not very good at c++. Can you give me CMakeLists. txt? I just got in touch with C++ programming in linux. Thank you very much for your help.

**Comment by SyGoing** [comment]
hello@leemengxing ，I have add a CMakeLists.txt ,you can try it

**Comment by leemengxing** [comment]
thank you a lot，your help helped me a lot.

**Comment by SyGoing** [comment]
If so, please star it
